#!/usr/bin/env node
/**
 * RO CSS Bundler (auto-discovery)
 *
 * - Includes ALL top-level *.css files in /css (except bundle.css)
 * - Includes all *.css inside NN-* directories (e.g., 10-components/)
 * - Excludes any directory named "_legacy" (and its children)
 * - Orders:
 *    1) NN-*.css files sorted by NN
 *    2) NN-* directories sorted by NN, inner files A→Z
 *    3) Non-numbered top-level *.css files A→Z (e.g., virgorises.css)
 * - Adds per-section banners:  /*# source: <relative path> *\/
 * - Preserves ANY comment that starts with "/*#" (bundle header + banners)
 * - Strips all other comments; light whitespace tidy
 *
 * Rebuild with:  node tools/build-css.mjs
 */

import fs from "fs";
import path from "path";

const projectRoot = path.resolve(".");
const cssDir = path.join(projectRoot, "css");
const outPath = path.join(cssDir, "bundle.css");

const isCss = (p) => p.toLowerCase().endsWith(".css");
const banner = (p) => `/*# source: ${p} */`;
const normNL = (s) => s.replace(/\r\n/g, "\n");

// Extract leading order number (e.g., "10-components" -> 10, "00-vars.css" -> 0)
function orderOf(name) {
  const m = /^(\d+)[-_]/.exec(name);
  return m ? parseInt(m[1], 10) : null; // null means "no numeric order"
}

function readText(p) {
  try { return fs.readFileSync(p, "utf8"); }
  catch { return ""; }
}

// --- Discover entries ---

const topFiles = [];
const numDirs  = [];  // NN-* directories
const numFiles = [];  // NN-*.css top-level files
const otherTop = [];  // non-numbered top-level *.css (e.g., virgorises.css)

for (const d of fs.readdirSync(cssDir, { withFileTypes: true })) {
  if (d.name === "bundle.css") continue;        // skip output
  if (d.isDirectory() && d.name === "_legacy") continue; // ignore legacy bucket

  if (d.isFile()) {
    if (!isCss(d.name)) continue;
    const ord = orderOf(d.name);
    if (ord != null) numFiles.push({ name: d.name, full: path.join(cssDir, d.name), order: ord });
    else otherTop.push({ name: d.name, full: path.join(cssDir, d.name) });
    continue;
  }

  if (d.isDirectory()) {
    const ord = orderOf(d.name);
    if (ord != null) numDirs.push({ name: d.name, full: path.join(cssDir, d.name), order: ord });
    // any non-numbered directories are ignored (by convention)
  }
}

// Sort groups
numFiles.sort((a,b) => (a.order - b.order) || a.name.localeCompare(b.name));
numDirs .sort((a,b) => (a.order - b.order) || a.name.localeCompare(b.name));
otherTop.sort((a,b) => a.name.localeCompare(b.name));

// --- Build segments ---

const segments = [];

// Header (every line starts with /*# so we preserve all)
segments.push(
  `/*# RO bundle.css */\n` +
  `/*# Rebuild with: node tools/build-css.mjs */\n` +
  `/*# Autogenerated: do not edit this file directly */\n`
);

// 1) Numbered top-level files
for (const f of numFiles) {
  const rel = f.name;
  const txt = normNL(readText(f.full)).trim();
  segments.push(`${banner(rel)}\n${txt}\n`);
}

// 2) Numbered directories (include *.css A→Z)
for (const dir of numDirs) {
  const files = fs.readdirSync(dir.full)
    .filter(fn => isCss(fn))
    .sort((a,b) => a.localeCompare(b));
  for (const fn of files) {
    const rel = path.join(dir.name, fn);
    const abs = path.join(dir.full, fn);
    const txt = normNL(readText(abs)).trim();
    segments.push(`${banner(rel)}\n${txt}\n`);
  }
}

// 3) Other top-level *.css (non-numbered)
/*
for (const f of otherTop) {
  const rel = f.name; // e.g., virgorises.css, vrw3schoolsnavbar.css
  const txt = normNL(readText(f.full)).trim();
  segments.push(`${banner(rel)}\n${txt}\n`);
}
*/
// Join with a blank line between sections
const joined = segments.join("\n");

// --- Comment filtering ---
// Keep ANY comment that starts with /*# (bundle header + per-file banners).
// Strip all other comments in two phases to avoid nested comment issues.
const keepHashComments = joined
  .replace(/\/\*(?!#)/g, "/* STRIP:")        // mark comments not starting with /*#
  .replace(/\/\* STRIP:[\s\S]*?\*\//g, "");  // remove them

// Light whitespace cleanup (preserve structure and section gaps)
const pretty = keepHashComments
  .replace(/\n{3,}/g, "\n\n")   // collapse 3+ blank lines → 2
  .replace(/[ \t]{2,}/g, " ")   // collapse long runs of spaces
  .replace(/[ \t]+\n/g, "\n");  // trim trailing spaces at line ends

fs.writeFileSync(outPath, pretty, "utf8");
console.log(`wrote ${path.relative(projectRoot, outPath)} (${(pretty.length/1024).toFixed(1)} KB)`);

// Quick audit of what's included
/*
console.log("\nIncluded sections:");
for (const s of segments) {
  const m = /\/\*# source:\s+([^)]+)\*\//.exec(s);
  if (m) console.log(" -", m[1]);
}
*/
