name: Hub & Memo Stats

on:
  push:
    paths:
      - "data/**"
      - "tools/build-hub-stats.mjs"
      - "tools/aggregate-memos.mjs"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow commits back to the repo
    concurrency:
      group: hub-and-memos
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Build hub stats
        run: node tools/build-hub-stats.mjs

      - name: Aggregate memo focus
        run: node tools/aggregate-memos.mjs

      - name: Commit outputs
        run: |
          set -e
          # stage only if they exist and changed
          CHANGES="$(git status --porcelain -- out/hub_stats.json out/latest_rfcs.json out/memos_focus.json || true)"
          if [[ -n "$CHANGES" ]]; then
            git config user.name "osf-bot"
            git config user.email "bot@zeta-zero-cafe"
            git add out/hub_stats.json out/latest_rfcs.json out/memos_focus.json || true
            git commit -m "chore: update hub & memo stats"
            git push
          else
            echo "No changes to commit."
          fi
