name: pages build and deployment

on:
  push:
    branches: [ main ]
    paths:
      - "index.html"
      - "research_office.html"
      - "source.html"
      - "cafes/**"
      - "css/**"
      - "js/**"
      - "data/**"
      - "out/**"
      - ".github/workflows/static.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # If you have a build step (e.g. bundling CSS), do it here.
      - name: Build CSS bundle (optional)
        run: |
          if [ -f tools/build-css.mjs ]; then
            node tools/build-css.mjs || true
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
          # Exclude repo internals
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
